[package]
name = "keploy"
version = "0.1.0"
authors = ["\"TJ Maynes (Personal)\" <\"tj@tjmaynes.com\">"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
