[package]
name = "keploy"
version = "0.1.0"
authors = [
    "Dmitriy Dubson <d.dubson@gmail.com>",
    "TJ Maynes <tj@tjmaynes.com>"
]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "2.33.3"