name: CI
on:
  push:
    branches:
      - 'main'

jobs:
  ship_it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.200
      - name: 🔨 Install Dependencies 🔨
        run: sudo apt-get update && sudo apt-get install make
      - name: 🚀 Ship it 🚀
        run: make ship_it
